# Generated by Django 5.0.6 on 2024-06-28 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_name', models.CharField(max_length=20)),
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('max', models.IntegerField()),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.student')),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.subject')),
            ],
        ),
    ]
