# Generated by Django 5.0.6 on 2024-06-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='roll',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='sub',
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=20)),
                ('mark', models.IntegerField()),
                ('max', models.IntegerField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
