# Generated by Django 5.0.6 on 2024-06-29 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_remove_mark_roll_remove_mark_sub_studentmark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('max', models.IntegerField()),
                ('sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyapp.subject')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_marks', to='studyapp.student')),
                ('st_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='st_name_marks', to='studyapp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
    ]
