# Generated by Django 5.0.6 on 2024-06-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_student_mark_delete_studentmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='st_name',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='roll',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
