# Generated by Django 5.0.6 on 2024-06-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0004_remove_mark_st_name_remove_mark_roll_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('st_name', models.CharField(default='valid Python', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='mark',
            old_name='max',
            new_name='max_mark',
        ),
    ]
