# Generated by Django 5.0.6 on 2024-06-29 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_student_rename_max_mark_max_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
