# Generated by Django 5.0.6 on 2024-06-29 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
