# Generated by Django 5.0.6 on 2024-06-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0008_delete_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
