# Generated by Django 5.0.6 on 2024-07-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=30, verbose_name='Student Name')),
                ('phy', models.IntegerField(verbose_name='Physics')),
                ('chem', models.IntegerField(verbose_name='Chemistry')),
                ('math', models.IntegerField(verbose_name='Maths')),
            ],
        ),
        migrations.RemoveField(
            model_name='mark',
            name='s_name',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='sub',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
