# Generated by Django 5.0.6 on 2024-07-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0011_studentmark_remove_mark_s_name_remove_mark_sub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50, verbose_name='File name: ')),
                ('file_upload', models.FileField(upload_to='uploads/notes')),
            ],
        ),
    ]
