# Generated by Django 5.0.6 on 2024-07-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0012_uploadfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_name',
            field=models.CharField(max_length=50, verbose_name='File name '),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='file_upload',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
